"""Evaluation-only check of GT USD materials under CPU Cycles."""
import bpy,json
from pathlib import Path
import numpy as np
from mathutils import Matrix
R=Path(__file__).resolve().parents[1];out=R/'results/ground_truth/material_check';out.mkdir(parents=True,exist_ok=True);bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.wm.usd_import(filepath=str(R.parent/'drone-web/scenes/world_lobby/lobby.usda'),import_materials=True,import_cameras=False,import_lights=True);s=bpy.context.scene;s.render.engine='CYCLES';s.cycles.device='CPU';s.cycles.samples=16;s.cycles.use_denoising=True;s.render.threads_mode='FIXED';s.render.threads=4;s.render.resolution_x=640;s.render.resolution_y=480;s.render.resolution_percentage=100;s.render.image_settings.file_format='PNG';s.view_settings.view_transform='AgX';s.view_settings.exposure=-10
if s.world is None:s.world=bpy.data.worlds.new('World')
s.world.use_nodes=True;s.world.node_tree.nodes.clear();bg=s.world.node_tree.nodes.new('ShaderNodeBackground');wo=s.world.node_tree.nodes.new('ShaderNodeOutputWorld');s.world.node_tree.links.new(bg.outputs[0],wo.inputs['Surface']);bg.inputs['Color'].default_value=(1,1,1,1);bg.inputs['Strength'].default_value=12000
c=bpy.data.cameras.new('GT_camera');co=bpy.data.objects.new('GT_camera',c);s.collection.objects.link(co);s.camera=co;c.sensor_width=36;c.lens=762.8/1280*36;c.sensor_fit='HORIZONTAL';v=json.loads((R/'results/ground_truth/independent_holdout_20/manifest.json').read_text())['views'][0];C=np.eye(4);C[:3,:3]=np.array(v['camera_rotation_world_from_optical'])@np.diag([1,-1,-1]);C[:3,3]=v['camera_position_world_m'];co.matrix_world=Matrix(C.tolist());s.render.filepath=str(out/'cycles_fixed_world.png');stats={'materials':len(bpy.data.materials),'images':len(bpy.data.images),'lights':len(bpy.data.lights),'materials_detail':[{'name':m.name,'nodes':[(n.type,n.name) for n in m.node_tree.nodes] if m.node_tree else []} for m in bpy.data.materials]};(out/'import_audit.json').write_text(json.dumps(stats,indent=2));bpy.ops.render.render(write_still=True);print('MATERIAL_CHECK_DONE',stats['materials'],stats['images'],stats['lights'])
